### PR TITLE
Pec gh 146

### PR DESCRIPTION
**Pull request by pecastro**

### CODE REVIEW

**Comment by clemsos** [comment]
Thanks for the PR !  works great :+1: Do you think we also need to store positions after running a new layout for the network ?

**Comment by clemsos** [comment]
Sorry i messed up with git so ended up with a 2nd PR fot his issue #151 :sob:

**Comment by pecastro** [comment]
I think the store positions only makes sense in the preset layout. Right now the commit will make it store for any layout you're right. So perhaps we can contain it just to be active in the 'preset' one.
I think that further down the line it would be great to be able to store the generated automatic layouts but I don't see that as a priority now ...
I'll push a fix for this ...

**Comment by clemsos** [comment]
OK. Currently positions are stored only when you move manually, not when you apply a layout. What I thought is to add a "save positions" button somewhere, so when you think the layout is fine you can store it once and for all.

One issue is multi-user. If one person is moving nodes on a graph, it will reflect on the other's screen (app is reactive). It can be annoying when 2 people are looking at the same graph and moving nodes around

**Comment by clemsos** [comment]
@ungentilgarcon that is the goal of having views #153 : you can move nodes and save a separate state of the graph display while keeping position stored in the database untouched. I agree that current solution is a bit of a  weak compromise.

**Pull request merged**
