### PR TITLE
Rewrite the lib

### PR DESCRIPTION
**Pull request by clemsos**
This is a major rewriting that impacts the complete logic of the lib.

The new structure is as follow :

* corpus (CSV or db connectors)
* processors (engine for analysis like NLP, regexp, etc.)
*  visualizers (parsing and formatting for d3js)

The following code implement those changes

### CODE REVIEW

**Comment by clemsos** [comment]
Now we have to rewrite the tests as well !

**Comment by clemsos** [comment]
Ok, there is a whole new logic already ! Looks way cleaner.

**Comment by clemsos** [comment]
Now we have bash pipes. This is getting interesting

**Comment by clemsos** [comment]
Now just lack the test for the command line

**Comment by clemsos** [comment]
Let's ship !

**Comment by MAKIO135** [comment]
view template created with template parameter `editMode=false`  
needs improvement with #9

**Pull request merged**
